CREATE TABLE `calendar_year_dim` (
  `CALENDAR_YEAR_SEQ` int(11) NOT NULL,
  `YEAR` int(11) NOT NULL,
  `YEARCODE` varchar(20) NOT NULL,
  PRIMARY KEY (`CALENDAR_YEAR_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `country_dim` (
  `COUNTRY_SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `COUNTRY_CODE` varchar(20) NOT NULL,
  `COUNTRY_NAME` varchar(100) DEFAULT NULL,
  `DESCRIPTION` char(70) NOT NULL,
  `LAST_UPDATED` datetime DEFAULT NULL,
  `TABLE_CREATION` datetime DEFAULT NULL,
  PRIMARY KEY (`COUNTRY_SEQ`,`COUNTRY_CODE`)
) ENGINE=InnoDB AUTO_INCREMENT=292 DEFAULT CHARSET=utf8;

CREATE TABLE `exchange_rates_dim` (
  `EXCHANGE_SEQ` bigint(20) NOT NULL,
  `YEAR` int(11) NOT NULL,
  `CURRENCY_SYMBOL` varchar(15) NOT NULL,
  `CURRENCY_CODE` varchar(15) NOT NULL,
  `EXCHANGE_RATE` decimal(12,8) NOT NULL,
  `CURRENCY_NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`EXCHANGE_SEQ`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `gdp_fact` (
  `GDP_SEQ` bigint(20) NOT NULL,
  `CALENDAR_YEAR_ID` int(11) NOT NULL,
  `INDICATOR_ID` bigint(20) NOT NULL,
  `COUNTRY_ID` bigint(20) NOT NULL,
  `COUNTRY_CODE` varchar(20) NOT NULL,
  `EXCHANGE_ID` bigint(20) NOT NULL,
  `GDP_VALUE` bigint(20) DEFAULT NULL,
  `GDP_CURRENCY` varchar(20) NOT NULL,
  PRIMARY KEY (`GDP_SEQ`),
  KEY `exchange_rates_gdp_fact_fk` (`EXCHANGE_ID`),
  KEY `indicator_dim_gdp_fact_fk` (`INDICATOR_ID`),
  KEY `country_d_gdp_fact_fk` (`COUNTRY_ID`,`COUNTRY_CODE`),
  KEY `calendar_year_dim_gdp_fact_fk` (`CALENDAR_YEAR_ID`),
  CONSTRAINT `calendar_year_dim_gdp_fact_fk` FOREIGN KEY (`CALENDAR_YEAR_ID`) REFERENCES `calendar_year_dim` (`CALENDAR_YEAR_SEQ`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `country_d_gdp_fact_fk` FOREIGN KEY (`COUNTRY_ID`, `COUNTRY_CODE`) REFERENCES `country_dim` (`COUNTRY_SEQ`, `COUNTRY_CODE`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `exchange_rates_gdp_fact_fk` FOREIGN KEY (`EXCHANGE_ID`) REFERENCES `exchange_rates_dim` (`EXCHANGE_SEQ`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `indicator_dim_gdp_fact_fk` FOREIGN KEY (`INDICATOR_ID`) REFERENCES `indicator_dim` (`INDICATOR_SEQ`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `gdpsource` (
  `Country Name` varchar(50) DEFAULT NULL,
  `Country Code` varchar(50) DEFAULT NULL,
  `INDICATOR_CODE` varchar(50) DEFAULT NULL,
  `Time` int(11) DEFAULT NULL,
  `GDP value for total year in USD` decimal(28,10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `indicator_dim` (
  `INDICATOR_SEQ` bigint(20) NOT NULL AUTO_INCREMENT,
  `INDICATOR_NAME` varchar(150) NOT NULL,
  `INDICATOR_DESC` varchar(800) NOT NULL,
  `INDICATOR_CODE` varchar(60) NOT NULL,
  `INDICATOR_DATASOURCE` varchar(200) NOT NULL,
  PRIMARY KEY (`INDICATOR_SEQ`),
  KEY `w_indicator_d_idx` (`INDICATOR_NAME`,`INDICATOR_CODE`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8;

